twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        App\Blog\Infrastructure\Rendering\Components\: 'components/blog/'
        App\Team\Infrastructure\Rendering\Components\: 'components/team/'
