twig:
    file_name_pattern: '*.twig'
    globals:
        ga_app_name: '%env(GA_APP_NAME)%'
        ga_measurement_id: '%env(GA_MEASUREMENT_ID)%'

when@test:
    twig:
        strict_variables: true
