twig_component:
    anonymous_template_directory: 'components/'
    defaults:
        App\OpenSource\Infrastructure\Rendering\Components\: 'components/open-source/'
        App\Website\Infrastructure\Rendering\Components\: 'components/home/'
