services:
  php:
    build:
      context: .
      target: frankenphp_prod
    environment:
      APP_SECRET: ${APP_SECRET}
      DEFAULT_URI: ${DEFAULT_URI}
      GA_APP_NAME: ${GA_APP_NAME}
      GA_MEASUREMENT_ID: ${GA_MEASUREMENT_ID}
