name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: install ssh keys
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_ed25519
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: connect pull and build
      run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "./web/bakslash/deploy.sh"
    - name: cleanup
      run: rm -rf ~/.ssh
